# Generated by Django 5.0.4 on 2024-05-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('population', models.PositiveIntegerField()),
                ('area', models.FloatField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
